# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagondrawing',
            name='ok_date',
            field=models.DateField(),
        ),
    ]
