# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0005_auto_20170419_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagondrawing',
            name='id',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='wagondrawing',
            name='posart1_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=19),
        ),
    ]
