# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0006_auto_20170525_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagondrawing',
            name='posart1_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
