# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0007_auto_20170525_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagondrawing',
            name='uuid',
        ),
        migrations.AddField(
            model_name='wagondrawing',
            name='iid',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='wagondrawing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
