# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0008_auto_20170529_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagondrawing',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
