# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0011_auto_20170801_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagondrawing',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
