# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0012_auto_20170801_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wagon_number', models.IntegerField(default=0)),
                ('ok_date', models.DateField()),
                ('product', models.CharField(max_length=30)),
                ('sortnr', models.IntegerField(default=0)),
                ('gfnr', models.CharField(max_length=15)),
                ('posart1_quantity', models.IntegerField(blank=True, default=0)),
                ('iid', models.CharField(default=0, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('typ', models.CharField(max_length=50)),
            ],
        ),
    ]
