# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0013_workerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=1)),
            ],
        ),
    ]
